#add the files to index
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/110CYL067.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/110CYL068.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/110CYL069.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/110CYL070.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/110CYL071.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/110CYL072.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/110CYL200.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/111344.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/111348.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/111349.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/111359.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/111363.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/111364.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/111367.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/111369.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/111371.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/111373.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/111375.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/111377.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/111380.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/111381.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/111382.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/111393.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/111394.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/111399.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/111400.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/111404.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/111406.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/111410.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/111414.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/111422.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/111424.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/111425.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/111428.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/112C-L012.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/112C-L013.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/112C-L014.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/112C-L015.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/112C-L016.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/113CWL017.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/113CWL018.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/114423.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/114424.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/114428.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/114433.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/114435.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/114439.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/114440.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/114441.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/114442.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/114445.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/114446.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/114447.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/114448.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/114450.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/114452.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/114CUL057.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/114CUL058.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/114CUL059.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/114CUL060.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/115CVL035.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/115CVL036.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/115CVL037.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/116CUL032.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/116CUL033.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/116CUL034.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/117CWL008.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/117CWL009.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/118CWL048.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/118CWL049.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/118CWL050.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/119CWL041.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/12030.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/12174.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/12176.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/1399.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/1400.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/1401.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/1402.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/1403.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/1468-6708-3-1.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/1468-6708-3-3.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/1471-2091-2-9.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/1471-213X-1-1.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/1471-230X-2-21.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/173252.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/173906.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/174124.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/175448.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/175814.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/175816.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/175841.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/176581.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/20000410_nyt-NEW.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/20000415_apw_eng-NEW.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/20000419_apw_eng-NEW.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/20000424_nyt-NEW.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/20020731-nyt.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/210343.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/211401.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/211402.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/21257.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/218920.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/219122.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/219123.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/219257.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/221197.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/230685.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/234267.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/234783.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/23559.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/49059.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/50307.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/52201.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/52555.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/52713.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/52998.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/52999.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/53536.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/53555.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/54261.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/54262.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/54263.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/54536.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/54537.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/602CZL285.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/8885.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/9066.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/9085.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/9159.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/9191.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/A1.E1-NEW.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/A1.E2-NEW.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/Acephalous-Cant-believe.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/Acephalous-Internet.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/A_defense_of_Michael_Moore.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/alumnifund1.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/AMC2.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/anth_essay_4.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/Anti-Terrorist.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/Ant_Robot.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/appalachian1.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/Apply.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/Article247_327.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/Article247_328.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/Article247_3500.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/Article247_400.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/Article247_500.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/Article247_66.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/ArticleIP_1059.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/ArticleIP_1060.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/aspca1.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/att2.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/audubon1.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/audubon2.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/A_Wasted_Day.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/Bartok.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/Black_and_white.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/blog-jet-lag.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/blog-monastery.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/blog-new-year's-resolutions.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/blog-varsity-athletics.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/captured_moments.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/Cartoonist_services.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/ch5.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/chapter-10.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/chZ.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/CUP1.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/CUP2.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/Dear_e-mail_user.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/defenders5.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/detroit.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/Earnings_Season_Underway.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/Effing-Idiot.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/ENRON-pearson-email-25jul02.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/enron-thread-159550.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/Env_Prot_Agency-nov1.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/Fastest_Reader.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/FBI_urgent.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/fcic_final_report_conclusions.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/Fermentation_Eminent-Domain.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/Fermentation_HR5034.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/Globa_Professional_Directory.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/guidedogs1.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/HistoryGreek.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/HistoryJerusalem.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/HistoryLasVegas.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/Homosexuality.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/hotel-california.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/How_soon-Fans.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/How_soon-Lebron-James.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/hsus4.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/IFAW1.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/IntroDublin.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/IntroHongKong.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/Italy.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/jokes10.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/jokes11.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/jokes12.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/jokes13.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/jokes14.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/jokes15.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/jokes16.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/jokes1.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/jokes2.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/jokes3.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/jokes4.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/jokes5.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/jokes6.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/jokes7.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/jokes8.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/jokes9.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/journal.pbio.0020001.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/JurassicParkIV-INT.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/JurassicParkIV-Scene_1.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/JurassicParkIV-Scene_3.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/JurassicParkIV-Scene_4.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/JurassicParkIV-Scene_5.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/Laptop_Bags.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/lessig_blog-carbon.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/lists-003-2114716.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/lists-003-2121270.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/lists-003-2125109.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/lists-003-2129640.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/lists-003-2133315.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/lists-003-2137010.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/lists-003-2144868.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/lists-003-2148080.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/lists-003-2152883.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/lists-003-2171003.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/lists-003-2173878.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/lists-003-2180740.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/lists-003-2183485.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/lists-003-2205935.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/lists-034-10062451.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/lists-034-10066763.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/lists-034-10069772.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/lists-034-10073419.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/lists-034-10077455.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/lists-034-10082707.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/lists-046-11485666.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/lists-046-11489622.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/lists-046-11493928.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/lists-046-11506817.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/lists-046-12119260.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/lists-046-12122969.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/lists-046-12130258.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/lists-046-12133410.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/lists-046-12139072.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/lists-046-12142206.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/lists-046-12146425.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/lists-046-12151335.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/lists-046-12155427.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/lists-046-12158926.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/lists-046-12162937.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/littleshelter2.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/lw1.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/Madame_White_Snake.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/Mailbox_Upgrade.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/marine1.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/Nathans_Bylichka.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/new_clients.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/NWF1.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/NYTnewswire1.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/NYTnewswire2.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/NYTnewswire3.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/NYTnewswire4.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/NYTnewswire5.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/NYTnewswire6.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/NYTnewswire7.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/NYTnewswire8.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/NYTnewswire9.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/Ohio_Steel.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/pirates.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/pmed.0010029.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/Postal_Rate_Comm-ReportToCongress2002WEB.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/Protocol_Regarding_Access.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/record_volume.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/Re_ Job Offer.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/rr166.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/rybczynski-ch3.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/Secret_Shopper.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/Seedbombing.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/SEO.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/SgtCassandra.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/sucker.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/The_Black_Willow.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/Tupelo-Honey-Cafe.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/tweets1.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/tweets2.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/ucb10.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/ucb11.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/ucb12.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/ucb14.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/ucb15.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/ucb1.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/ucb20.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/ucb21.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/ucb22.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/ucb23.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/ucb24.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/ucb25.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/ucb26.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/ucb27.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/ucb28.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/ucb29.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/ucb2.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/ucb30.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/ucb31.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/ucb3.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/ucb40.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/ucb41.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/ucb42.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/ucb43.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/ucb44.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/ucb45.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/ucb46.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/ucb47.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/ucb48.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/ucb49.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/ucb4.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/ucb50.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/ucb51.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/ucb52.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/ucb53.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/ucb54.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/ucb6.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/ucb8.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/ucb9.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/united1.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/Uprooted_Bike.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/Uprooted_Farming-on-Sand.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/vampires.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/VOL15_3.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/warner1.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/WhatToHongKong.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/WhereToHongKong.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/wildelifewatch1.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/wsj_0006.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/wsj_0026.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/wsj_0027.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/wsj_0032.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/wsj_0068.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/wsj_0073.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/wsj_0106.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/wsj_0120.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/wsj_0124.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/wsj_0127.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/wsj_0132.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/wsj_0135.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/wsj_0136.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/wsj_0144.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/wsj_0150.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/wsj_0151.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/wsj_0152.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/wsj_0157.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/wsj_0158.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/wsj_0159.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/wsj_0160.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/wsj_0161.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/wsj_0165.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/wsj_0167.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/wsj_0168.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/wsj_0169.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/wsj_0171.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/wsj_0172.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/wsj_0173.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/wsj_0175.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/wsj_0176.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/wsj_0184.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/wsj_0187.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/wsj_0189.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/wsj_1640.mrg-NEW.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/wsj_2465.txt
/home/alberto/Escritorio/BusquedaDeInformacion/corpus/wwf12.txt
